baseurl: /docs
title: Matatika API Docs
logo: "/images/Logo-small.svg"
permalink: pretty

theme: just-the-docs
color_scheme: matatika

kramdown:
  toc_levels: [2]

plugins:
  - jekyll-feed

exclude:
    - .sass-cache/
    - .jekyll-cache/
    - gemfiles/
    - Gemfile
    - Gemfile.lock
    - vendor
    - docker-compose.yml
    - README.md
    - Makefile
    - azure-pipelines.yml
    - build-docs.sh
    - restdocs-to-postman/