title: Matatika API Docs
logo: "https://www.matatika.com/wp-content/themes/matatika/images/Logo-small.svg"
permalink: pretty

# https://docs.spring.io/spring-restdocs/docs/current/reference/html5/#working-with-markdown-limitations
markdown: redcarpet
redcarpet:
  extensions: ["tables"]

aux_links:
  "Matatika site":
    - "www.matatika.com"

theme: just-the-docs
plugins:
  - jekyll-feed

exclude:
    - .sass-cache/
    - .jekyll-cache/
    - gemfiles/
    - Gemfile
    - Gemfile.lock
    - vendor
    - docker-compose.yml
    - README.md
    - Makefile
    - azure-pipelines.yml
    - build-docs.sh