title: Matatika Documentation
logo: /assets/img/Logo-small.svg
permalink: pretty

defaults:
  - scope:
      path: content/**/*.md
    values:
      layout: default

matatika:
  links:
    www: http://www-localhost.matatika.com
    app: http://localhost:3443
    catalog: http://localhost:8080/api

theme: just-the-docs
color_scheme: matatika

kramdown:
  toc_levels: [2]

plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor
  - docker-compose.yml
  - README.md
  - Makefile
  - azure-pipelines.yml
  - build-docs.sh
  - restdocs-to-postman/

# build
strict_front_matter: true

# serve
livereload: true
