# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- dev

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
    
- task: DownloadReleaseArtifact@1
  inputs:
    artifactName: '$(System.DefaultWorkingDirectory)/matatika-sit/src/target.zip'
    artifactStorageLocation: '$(System.ArtifactsDirectory)'
    unzipFile: true

- script: ls $(Pipeline.Workspace)
  displayName: 'Verify pipeline artifact download'