trigger:
- master
- dev

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)/s'
    artifact: 'src'
    publishLocation: 'pipeline'