version: '3'
services:
    jekyll-docs:
        image: jekyll/minimal:4.1.0
        ports:
            - 4000:4000
        volumes:
            - ${PWD}:/srv/jekyll
            - ${PWD}/vendor/bundle:/usr/local/bundle
        command: jekyll serve --config _config.yml
