version: "3"
services:
  jekyll-docs:
    image: jekyll/jekyll:4.2.2
    ports:
      - 4000:4000
      - 35729:35729
    volumes:
      - ${PWD}:/srv/jekyll
      - ${PWD}/vendor/bundle:/usr/local/bundle
    command: jekyll serve --incremental
    environment:
      - JEKYLL_ROOTLESS=true
